### PR TITLE
fix: update json-diff to working version

### PR DESCRIPTION
**Pull request by ivanoats**
Resolves a `TypeError: Cannot read property 'key' of null` with an update of the json-diff package to the latest version/

### CODE REVIEW

**Comment by jfjonsson** [comment]
Also getting this error. @ivanoats any workaround while this is reviewed?

_side note: should the test coverage decrease when only package.json and lock change? 🤔_

**Comment by ivanoats** [comment]
@jfjonsson The only "workaround" I had was downloading the package locally and upgrading as in this PR, sorry.

**Comment by gburgett** [comment]
Thanks!  Will merge

**Comment by gburgett** [comment]
Released in v0.10.3

**Pull request merged**
